version: '3.4'
services:
  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 6069
    volumes:
      - demo-volume-2:/app
    ports:
      - 6069:6069
    restart: always
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery --app celery_queue worker --loglevel=debug --pool=solo -E --logfile=logs/celery_main.log
    volumes:
      - demo-volume-2:/app
    restart: always
    depends_on:
      - app
      - redis
volumes:
 demo-volume-2:
   #external: true
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app