version: '3.4'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: always
  chroma:
    image: chromadb/chroma
    ports:
      - "6062:8000"
    volumes:
      - stroage-volume:/chroma/chroma
    restart: always
  app:
    container_name: app
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 6069
    volumes:
      - demo-volume:/app
    ports:
      - 6069:6069
    restart: always
    #depends_on:
    #  - redis
  celery_worker:
    container_name: celery_worker
    build: .
    command: celery --app celery_queue worker --loglevel=info --pool=solo -E --logfile=logs/celery_main.log
    volumes:
      - demo-volume:/app
    depends_on:
      - redis
      - app
volumes:
  demo-volume:
   #external: true
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${PWD}/app

  stroage-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/ikegaidevuser/storage
